language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_dev.gemfile
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.1.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_dev.gemfile
